<?php

/**
 * @file
 * Module Swing Jammerz showing Google Maps Block
 */

/**
 * Implements hook_block_info().
 */
function sj_gmaps_block_info() {
  $blocks = array();
  
  $blocks['sj_gmaps'] = array(
    'info' => t('Swing Jammerz - Google Maps')
  );

  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function sj_gmaps_block_configure($delta='') {
  $form = array();

  switch($delta) {
    case 'sj_gmaps' :
    // Text field form element
    $form['text_body'] = array(
      '#type' => 'text_format',
      '#title' => t('Enter your text here in WYSIWYG format'),
      '#default_value' => variable_get('sj_gmaps_block', ''),
    );
      
    break;
  }
  
  return $form;
}

/**
 * Implements hook_block_save().
 */
function sj_gmaps_block_save($delta = '', $edit = array()) {
  switch($delta) {
    case 'sj_gmaps' :
    variable_set('sj_gmaps_block', $edit['text_body']['value']);
      
    break;
  }
}

/**
 * Implements hook_block_view().
 */
function sj_gmaps_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'sj_gmaps' :
      $block['content'] = sj_gmaps_view();
      break;
  }

  return $block;
}

/**
 * Google maps view
 *
 * @return array 
 */
function sj_gmaps_view() {
  drupal_add_js('http://maps.googleapis.com/maps/api/js?sensor=false&callback=initialize', array('scope' => 'footer'));
  
  $block = array();
  $text = variable_get('sj_gmaps_block', '');
  if (strpos($text, '{locations}')) {
    // Collect lessons
    $places = db_select('sj_places', 'p')
            ->fields('p')
            ->condition('p.year', get_season_year())
            ->condition('p.enabled', true)
            ->execute()
            ->fetchAll();
    
    $list = '';
    if (count($places)) {
      $list .= '<div id="gmap-places">';
      foreach ($places as $key => $place) {
        $list .= '<div class="place">'
                . '<h3 class="open-marker" data-key="' . $key . '">' . $place->name . '</h3>'
                . '<p>' . $place->address . '<br/>'
                . $place->postcode . ' ' . $place->city
                . '</div>';
      }
      $list .= '</div><div class="clear"></div>';
    }
    
    $text = str_replace('{locations}', $list, $text);
  }
  
  if (strpos($text, '{gmap}')) {
    $text = str_replace('{gmap}', '<div id="map_wrapper">
      <div id="map_canvas" class="mapping"></div>
      </div>', $text);
    
    drupal_add_js(drupal_get_path('module', 'sj_gmaps') .'/js/gmaps.js');
    drupal_add_js(array('sj_gmaps' => array('locations' => sort_locations($places))), 'setting');
  }
  
  // Block output in HTML with div wrapper
  $block = array(
    'message' => array(
      '#type' => 'markup',
      '#markup' => $text,
      '#suffix' => '',
    ),
  );

  return $block;
}

/**
 * Sort locations in array
 *
 * @param array $places
 */
function sort_locations(array $places) {
  $locations = array();
  foreach ($places as $place) {
    $locations[] = array($place->name, $place->address, floatval($place->latitude), floatval($place->longitude));
  }
  
  return json_encode($locations);
}