# Pull gems from RubyGems
source 'https://rubygems.org'

# Radix gems
group :assets do
    gem 'sass-rails',   '~> 3.2.5'
    gem 'coffee-rails', '~> 3.2.2'
    gem 'uglifier', '>= 1.2.4'
    gem 'bootstrap-sass', '~> 2.0.3.1'
    gem 'compass', '>= 0.12.2'
    gem 'bootstrap-sass', '>= 3.0.3.0'
    gem 'compass_radix', '>= 3.0.1'
    gem 'bootswatch-rails'
end